Uploaded a Application example that uses the WifiCam example
yoursunny/esp32cam pull request #19
Opened 2021-09-30 20:37 UTC by dolendravikas

This is a python based application where the face and eye detection algorithms can be locally on the personal computer where this python file is running. The only thing care should be taken is that both the esp32 cam module and the personal computer should be connected to the same network.

2021-09-30 20:47 UTC, yoursunny requested changes

2021-09-30 20:47 UTC, yoursunny commented on examples/applications/Face&EyesDetection.py
> +steps to exicute this application:
I see many typos in this comment. Please run spell check.

2021-09-30 20:47 UTC, yoursunny commented on examples/applications/Face&EyesDetection.py
> +url='http://xxx.xxx.xxx.xxx/cam-lo.jpg' #change the IP address to the IP address to which the ESP32 cam is connected to
This should be abstracted as a command line flag. Don't ask user to modify code.

2021-09-30 20:47 UTC, yoursunny commented on examples/applications/Face&EyesDetection.py
> +    img_resp=urllib.request.urlopen(url)
Ensure code style conforms to PEP 8.
You may use `autopep8` command for that.

2021-09-30 20:47 UTC, yoursunny commented on examples/applications/Face&EyesDetection.py
> +    img=cv2.imdecode(imgnp,-1)
`cv2` is an external dependency.
Please include a `Pipfile` so that the dependencies can be installed via `pipenv`.

2021-09-30 20:47 UTC, yoursunny commented on examples/applications/Face&EyesDetection.py
> +'''
In Arduino library, `examples` directory is intended for Arduino examples.
This is not an Arduino example, so it should go into `extras` directory, which is ignored by Arduino IDE.
See https://arduino.github.io/arduino-cli/0.19/library-specification/

2021-10-01 07:55 UTC, yoursunny requested changes

2021-10-01 07:55 UTC, yoursunny commented on examples/applications/Face&EyesDetection.py
> +'''
Delete this file. Don't add two copies of the same file.

2021-10-01 07:55 UTC, yoursunny commented on extras/applications/Face&EyesDetection.py
> +4. Open the serial monitor and note down the IP address and change the 18th line of this code with that IP address
This step is no longer accurate.

2021-10-01 07:55 UTC, yoursunny commented on extras/applications/Face&EyesDetection.py
> +url = 'http://'
Simplify as:

```python
url = 'http://' + sys.argv[1] + '/cam-lo.jpg'
```

2021-10-01 07:55 UTC, yoursunny commented on extras/applications/Face&EyesDetection.py
> +##'''cam.bmp / cam-lo.jpg /cam-hi.jpg / cam.mjpeg '''
Delete dead code.

2021-10-01 08:12 UTC, dolendravikas commented on extras/applications/Face&EyesDetection.py
> +4. Open the serial monitor and note down the IP address and change the 18th line of this code with that IP address
can I know which step is in accurate

2021-10-01 08:14 UTC, yoursunny commented on extras/applications/Face&EyesDetection.py
> +4. Open the serial monitor and note down the IP address and change the 18th line of this code with that IP address
"change 18th line" is inaccurate.

2021-10-02 15:52 UTC, yoursunny commented
I tested the application but could not get it to work.

```shell
$ docker run -it --rm --network host -v $(pwd):/app -w /app michaelbalser/python-opencv bash

root@sunnyJ:/app# lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               1
Model name:          Cortex-A57
Stepping:            r1p1
CPU max MHz:         1479.0000
CPU min MHz:         102.0000
BogoMIPS:            38.40
L1d cache:           128 KiB
L1i cache:           192 KiB
L2 cache:            2 MiB
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

root@sunnyJ:/app# apt update && apt install -y --no-install-recommends gdb

root@sunnyJ:/app# python --version
Python 3.9.7

root@sunnyJ:/app# pip install pipenv
Successfully installed backports.entry-points-selectable-1.1.0 certifi-2021.5.30 distlib-0.3.3 filelock-3.2.0 pipenv-2021.5.29 platformdirs-2.4.0 six-1.16.0 virtualenv-20.8.1 virtualenv-clone-0.5.7

root@sunnyJ:/app# cd extras/applications/FaceAndEyesDetection/

root@sunnyJ:/app/extras/applications/FaceAndEyesDetection# pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

root@sunnyJ:/app/extras/applications/FaceAndEyesDetection# pipenv run python Face\&EyesDetection.py 192.168.5.56
Illegal instruction (core dumped)

root@sunnyJ:/app/extras/applications/FaceAndEyesDetection# pipenv run gdb --silent --args python Face\&EyesDetection.py 192.168.5.56
Reading symbols from python...
(gdb) run
Starting program: /root/.local/share/virtualenvs/FaceAndEyesDetection-PV0Kz0Zw/bin/python Face\&EyesDetection.py 192.168.5.56
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000007fa0d23f54 in gotoblas_dynamic_init ()
   from /root/.local/share/virtualenvs/FaceAndEyesDetection-PV0Kz0Zw/lib/python3.9/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-32ff4d91.3.13.so
```

I also tried distro-provided OpenCV packages, and it doesn't work either:

```shell
$ docker run -it --rm --network host -v $(pwd):/app -w /app debian:bullseye bash

root@sunnyJ:/app# apt update && apt install -y --no-install-recommends python3-opencv

root@sunnyJ:/app# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.5.1'

root@sunnyJ:/app# cd extras/applications/FaceAndEyesDetection/

root@sunnyJ:/app/extras/applications/FaceAndEyesDetection# python3 Face\&EyesDetection.py 192.168.5.56
Traceback (most recent call last):
  File "/app/extras/applications/FaceAndEyesDetection/Face&EyesDetection.py", line 22, in <module>
    cv2.data.haarcascades+'haarcascade_frontalface_default.xml')
AttributeError: module 'cv2' has no attribute 'data'
```

2021-10-02 15:58 UTC, yoursunny requested changes

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +'''
Rename this file as `extras/FaceAndEyesDetection/main.py`. Don't have `&` in the filename because it requires quoting in bash.

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +steps to execute this application:
Put these instructions in README.md of the same folder, not as code comments.

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +1. Execute the WifiCam.ino file in ESP32 cam module which is available at examples->WifiCam->WifiCam.ion.
typo ion

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +2. Before executing the WifiCam example, make sure that the wifi credentials are saves accordingly.
typo saves

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +4. Open the serial monitor and note down the IP address and change the 18th line of this code with that IP address
No need to change code

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +##'''cam.bmp / cam-lo.jpg /cam-hi.jpg / cam.mjpeg '''
delete dead code

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Pipfile
> +[[source]]
It seems that pipenv cannot install OpenCV automatically. If you think it's more appropriate to use distro-provided packages, you can delete the Pipfile and add instructions on installing `python3-opencv` and other necessary packages.

2021-10-02 15:58 UTC, yoursunny commented on extras/applications/FaceAndEyesDetection/Face&EyesDetection.py
> +url = 'http://'
Simplify these three lines to just one line.

2024-06-13 14:22 UTC, closed without merging